test the github workflow configs

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -1,30 +1,69 @@
+# name: Java CI with Maven
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#   pull_request:
+#     branches: [ "main" ]
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     services:
+#       mysql:
+#         image: mysql:8.0
+#         ports:
+#           - 3306:3306
+#         env:
+
+#           MYSQL_ROOT_PASSWORD: 123456
+#           MYSQL_DATABASE: school-reg
+      
+#         options: >-
+#           --health-cmd "mysqladmin ping --silent"
+#           --health-interval 10s
+#           --health-timeout 5s
+#           --health-retries 3
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       - name: Set up JDK 21
+#         uses: actions/setup-java@v2
+#         with:
+#           java-version: '21'
+#           distribution: 'temurin'
+
+#       - name: Set up MySQL driver dependency
+#         run: mvn dependency:resolve --file "Course Registration/pom.xml"
+
+#       - name: Wait for MySQL to be ready
+#         run: |
+#           while ! mysqladmin ping -h "127.0.0.1" --silent; do
+#             echo 'Waiting for MySQL...'
+#             sleep 5
+#           done
+
+ 
+#       - name: Build with Maven
+#         run: mvn -B package --file "Course Registration/pom.xml"
+#       - name: Test with Maven
+#         run: mvn test --file pom.xml
+
+
 name: Java CI with Maven
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "ft-course-3" ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ "ft-course-3" ]
 
 jobs:
   build:
     runs-on: ubuntu-latest
-
-    services:
-      mysql:
-        image: mysql:8.0
-        ports:
-          - 3306:3306
-        env:
-
-          MYSQL_ROOT_PASSWORD: 123456
-          MYSQL_DATABASE: school-reg
-      
-        options: >-
-          --health-cmd "mysqladmin ping --silent"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
 
     steps:
       - name: Checkout code
@@ -36,16 +75,7 @@ jobs:
           java-version: '21'
           distribution: 'temurin'
 
-      - name: Set up MySQL driver dependency
-        run: mvn dependency:resolve --file "Course Registration/pom.xml"
-
-      - name: Wait for MySQL to be ready
-        run: |
-          while ! mysqladmin ping -h "127.0.0.1" --silent; do
-            echo 'Waiting for MySQL...'
-            sleep 5
-          done
-
- 
       - name: Build with Maven
         run: mvn -B package --file "Course Registration/pom.xml"
+      - name: Test with Maven
+        run: mvn test --file pom.xml
